### PR TITLE
Translate menu entry Introduction to Accessibility to pt-BR

### PR DESCRIPTION
**Pull request by adielcristo**
Issue: https://github.com/w3c/wai-translations/issues/253

### CODE REVIEW

**Comment by israelcefrin** [comment]
Hi @adielcristo 

I think we could use the full term instead of only "accessibilidade" since this documentation focused on digital/online content, I would recommend to use the same term that previous translations are using:  "Acessibilidade da Web" with capital letter for both word. See the title from this URL: https://www.w3c.br/traducoes/wcag/wcag21-pt-BR/

Hence, the title could be reworded to "Introdução à Acessibilidade da Web"

**Comment by israelcefrin** [comment]
> > Hi @adielcristo
> > I think we could use the full term instead of only "accessibilidade" since this documentation focused on digital/online content, I would recommend to use the same term that previous translations are using: "Acessibilidade da Web" with capital letter for both word. See the title from this URL: https://www.w3c.br/traducoes/wcag/wcag21-pt-BR/
> > Hence, the title could be reworded to "Introdução à Acessibilidade da Web"
> 
> Hi @israelcefrin, although the title is slightly longer, I tried to keep the translation short as it will be used in the menu entry. I used the new Orthographic Agreement rules regarding capital letters, where only the first word uses capital letters (with exceptions). What do you think?

Agree! I've just realized this is the menu entry only, and even other menu items are not reflecting page titles. We can keep your recommendation.

**Review by remibetin — APPROVED** [review]
Thanks @adielcristo and @israelcefrin.

I will merge this pull request with https://github.com/w3c/wai-website/pull/924 when it is ready.

**Comment by remibetin** [comment]
Thanks @adielcristo @israelcefrin. I have merged this PR along with https://github.com/w3c/wai-website/pull/924

**Pull request merged**
