### PR TITLE
Remove rouge dependency and rebuild gem

### PR DESCRIPTION
**Pull request by remibetin**
From @howard-e's https://github.com/w3c/wai-website-data/pull/159

> Removed rouge as it was pinned to a version before [support was dropped for ruby < 2.7](https://github.com/rouge-ruby/rouge/releases/tag/v4.0.0) which also means it would prevent the wai-website from being updated beyond ruby 2.7.
>
> It is also already an [included dependency when using Jekyll](https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting).
>
> Rebuilt .gem using instructions in wai-gems/README.md.
>
> Confirmed this causes no build issues for wai-website using https://github.com/howard-e/wai-website/pull/1 ([build log](https://github.com/howard-e/wai-website/actions/runs/9402837047/job/25897871546)).

### CODE REVIEW

**Comment by howard-e** [comment]
Thanks. Updated https://github.com/w3c/wai-website/pull/542 and https://github.com/w3c/wai-website-theme/pull/98 to use this for testing

**Comment by remibetin** [comment]
@howard-e What do you think of my last comment? https://github.com/w3c/wai-website-data/pull/160#issuecomment-2194986208

**Comment by howard-e** [comment]
> @howard-e What do you think of my last comment? [#160 (comment)](https://github.com/w3c/wai-website-data/pull/160#issuecomment-2194986208)

Apologies, I had missed the comment.

> Or are we safe as long as the Gemfile.lock file is not updated?

Yep, this shouldn't be an issue as long that file isn't updated. I checked locally with several resources and also made 2 sample PRs which linked `_external/data` to this branch and they built without issue:
* https://github.com/w3c/wai-aria-practices/pull/332
* https://github.com/w3c/wai-policies-prototype/pull/527

**Comment by remibetin** [comment]
Thanks @howard-e I am merging this PR.

**Comment by remibetin** [comment]
@howard-e I'll let you update the other PRs consequently.

**Pull request merged**
