### PR TITLE
Cleanup and adding Spanish translations for review

### PR DESCRIPTION
**Pull request by yatil**

### CODE REVIEW

**Comment by yatil** [comment]
@rumoroso @cmuncharaz

Would you be so kind to double-check and/or suggest changes to the main menu items here. Most of them probably originate from a machine translation I did for testing, so I don’t expect wonders from it :-)

* [ ] `en: 'Accessibility Fundamentals'` -> `es: 'Fundamentos de accesibilidad'` ([line 3](https://github.com/w3c/wai-website-data/pull/21/files#diff-5911f38d99548fb0ac9e940763eeb013R3))
* [ ] `en: 'Planning & Policies'` -> `es: 'Planificación y Políticas'` ([line 116](https://github.com/w3c/wai-website-data/pull/21/files#diff-5911f38d99548fb0ac9e940763eeb013R116))
* [ ] `en: 'Design & Develop'` -> `es: 'Diseñar y Desarrollar'` ([line 150](https://github.com/w3c/wai-website-data/pull/21/files#diff-5911f38d99548fb0ac9e940763eeb013R150))
* [ ] `en: 'Test & Evaluate'` -> `es: 'Probar y Evaluar'` ([line 187](https://github.com/w3c/wai-website-data/pull/21/files#diff-5911f38d99548fb0ac9e940763eeb013R187))
* [ ] `en: 'Teach & Advocate'` -> `es: 'Enseñar y Promover'` ([line 218](https://github.com/w3c/wai-website-data/pull/21/files#diff-5911f38d99548fb0ac9e940763eeb013R218))
* [ ] `en: 'Standards/<wbr>Guidelines'` -> `es: 'Estándares/<wbr>Pautas'` ([line 259](https://github.com/w3c/wai-website-data/pull/21/files#diff-5911f38d99548fb0ac9e940763eeb013R259))

Thank you in advance!

/cc FYI @slhenry

**Comment by slhenry** [comment]
& @espinr

**Comment by espinr** [comment]
@yatil, +1 from my side. Thanks!

**Comment by rumoroso** [comment]
👍 from mine.

**Comment by yatil** [comment]
Thanks @espinr and @rumoroso. (And @cmuncharaz.)

I’ll merge the file and upload the changes.

**Pull request merged**
